#!/bin/bash
#echo Enter username for NFS account:
#read server
#useradd $server
#passwd $server
server=$1
sudo -u $server mkdir /home/${server}/dir1
sudo -u $server touch /home/${server}/file1
sudo -u $server touch /home/${server}/dir1/file2
sudo -u $server chmod 777 /home/${server}/dir1
sudo -u $server chmod 777 /home/${server}/file1
sudo -u $server chmod 777 /home/${server}/dir1/file2
echo file1 > /home/${server}/file1
echo file2 > /home/${server}/dir1/file2
echo "Destination IP: "
read dst_ip
echo "/home/${server} ${dst_ip}:/255.255.255.0(rw,no_root_squash)" >> /etc/exports
systemctl restart nfs
/usr/sbin/exportfs -v
